# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

# Definindo os caminhos de saída e ativos
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")  # Removendo o '/view/' do caminho

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("1001x561")
window.configure(bg = "#FFFFFF")

# Criando o canvas
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 561,
    width = 1001,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1001.0,
    561.0,
    fill="#73A5B1",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1001.0,
    63.0,
    fill="#505050",
    outline="")

# Criando a entrada de texto
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    501.5,
    120.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=218.0,
    y=69.0,
    width=567.0,
    height=100.0
)

# Criando botões
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=705.0,
    y=206.0,
    width=94.0,
    height=95.0
)

# Criando textos
canvas.create_text(
    334.0,
    8.0,
    anchor="nw",
    text="o QUE DESEJA COMUNICAR?",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 40 * -1)
)

canvas.create_text(
    202.0,
    307.0,
    anchor="nw",
    text="cOMUNICAÇÃO",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    717.0,
    307.0,
    anchor="nw",
    text="eXPRESSÕES",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    463.0,
    458.0,
    anchor="nw",
    text="rESPOSTAS RÁPIDAS",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    547.0,
    307.0,
    anchor="nw",
    text="tECLADO",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    648.0,
    458.0,
    anchor="nw",
    text="pALAVRAS BASICAS",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    219.0,
    458.0,
    anchor="nw",
    text="sAUDAÇÕES E fORMALIDADES",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

canvas.create_text(
    363.0,
    307.0,
    anchor="nw",
    text="nECESSIDADE",
    fill="#FFFFFF",
    font=("BebasNeue Regular", 20 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=202.0,
    y=206.0,
    width=94.0,
    height=95.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=528.0,
    y=206.0,
    width=94.0,
    height=95.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=264.0,
    y=357.0,
    width=94.0,
    height=95.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=474.0,
    y=357.0,
    width=94.0,
    height=95.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=659.0,
    y=357.0,
    width=94.0,
    height=95.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=357.0,
    y=206.0,
    width=94.0,
    height=95.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=125.0,
    y=81.0,
    width=77.0,
    height=77.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=857.0,
    y=81.0,
    width=77.0,
    height=77.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=20.0,
    y=81.0,
    width=77.0,
    height=77.0
)

window.resizable(False, False)
window.mainloop()
